[package]
name = "card-engine"
version = "0.1.0"
authors = ["Mason Smith <masonium@gmail.com>"]
license = "MIT"

[dependencies]
rand = "*"
termion = "1"
atty = "0.2"
lazy_static = "*"
ndarray = "0.9"
ndarray-rand = "0.5"
itertools = "0.6"
time = "0.1"