[package]
name = "card-engine"
version = "0.1.0"
authors = ["Mason Smith <masonium@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
rand = "*"
termion = "1"
atty = "0.2"
once_cell = "*"
ndarray = "*"
ndarray-rand = "*"
itertools = "*"
time = "*"
clap = "2"
